version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    container_name: mehedi
    environment:
      FLASK_APP: "/app/main.py"
      FLASK_ENV: "development"
    command: "flask run --host=0.0.0.0 --port=3000"
   
